# Generated by Django 3.0.5 on 2020-09-06 11:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_json', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('request_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=200)),
                ('default', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=200)),
                ('field_type_label', models.CharField(max_length=200)),
                ('is_removable', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('options_list', models.ManyToManyField(blank=True, to='api.OptionList')),
                ('options_url', models.ManyToManyField(blank=True, to='api.OptionsUrl')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('customerId', models.IntegerField(default=0)),
                ('law', models.CharField(max_length=200)),
                ('fields', models.ManyToManyField(blank=True, to='api.FieldsData')),
            ],
        ),
    ]
