# Generated by Django 3.0.5 on 2020-09-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200906_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsdata',
            name='options_list',
        ),
    ]
