# Generated by Django 3.0.5 on 2020-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fieldsdata_options_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsdata',
            name='options_list',
            field=models.ManyToManyField(to='api.OptionList'),
        ),
        migrations.AddField(
            model_name='fieldsdata',
            name='options_url',
            field=models.ManyToManyField(to='api.OptionsUrl'),
        ),
    ]
